plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mrobbie.majelismengaji'
    compileSdk 35

    defaultConfig {
        applicationId "com.mrobbie.majelismengaji"
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName "1.2.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            applicationIdSuffix ""
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
